"""Hand-authored complete response contrasts; expectation labels are review hypotheses."""
FIXTURES=[]
def add(tid,positive,old,new,fail_ids,off_topic):
    assert old in positive,tid
    FIXTURES.append({'task_id':tid,'variant':'positive','answer':positive,'min_score':.85,'must_pass':fail_ids})
    FIXTURES.append({'task_id':tid,'variant':'factual_error','answer':positive.replace(old,new), 'must_fail':fail_ids})
    FIXTURES.append({'task_id':tid,'variant':'off_topic','answer':off_topic,'max_score':.4})

add('lesson-builder__cn24_01',
'''Assume a senior-secondary class knows perpendicular lines and that no diagram has been supplied. State the goal: to prove a line perpendicular to a plane, it is enough to prove it perpendicular to two intersecting lines in that plane. Both intersections and the in-plane locations matter; one perpendicular in-plane line is not enough.
Draw the plane z=0 and a vertical line through O. Mark the x and y axes in the plane. Ask students to identify what must be proved for the vertical line to be a normal, then ask which two lines could witness it. Let them check the two right angles and explain why the axes intersect. Contrast the x-axis, which is perpendicular to the y-axis but lies in z=0: one right angle would give a false conclusion.
For a construction exercise, define a triangle ABC in the plane and a point P outside it. Ask what conditions on PA and two lines AB and AC would suffice, and distinguish given perpendicularities from facts still needing proof. Do not invent a diagram-specific auxiliary line for an unspecified figure.
Finish with an exit ticket: a line is perpendicular to AB and a parallel copy of AB. Does that certify perpendicularity to the plane? No: those do not provide two independent intersecting directions. Have students justify and correct the witness pair. If they use only one witness, revisit the x-axis counterexample; otherwise move to a new labelled figure.''',
'one perpendicular in-plane line is not enough','one perpendicular in-plane line is enough', ['C2','C6'],
'''To prove a line parallel to a plane, connect midpoints to construct an in-plane parallel line. Use a parallelogram if needed. Teach only this parallelism construction and then ask students to repeat it.''')

add('hinge-question-designer__cn29_06',
'''No student's actual work has been supplied, so the following is a hypothetical diagnostic sequence, not a diagnosis of a real learner. Use x^2-2x+c>=0 for every real x. Completing the square gives (x-1)^2+c-1, whose minimum occurs at x=1. Therefore c>=1 is necessary and sufficient.
First ask the student to explain “for every x” and contrast it with “for at least one x.” If they check only x=0, ask whether another input could fail; try x=1. If they understand the quantifier but do not know a strategy, prompt them to find the minimum or complete the square. If they choose that strategy but expand incorrectly, ask them to multiply out and compare coefficients. These branches separate conceptual, strategy and arithmetic evidence rather than assuming the cause from a final answer.
Ask the pupil to repair the argument in their own words. Transfer check: x^2-4x+c>=0 for every real x needs c>=4 because the minimum is c-4 at x=2. Check both necessity at the minimizing input and sufficiency from a nonnegative square. If the quantifier is still confused, compare one working input with a counterexample before advancing.''',
'Therefore c>=1 is necessary and sufficient.','Therefore c>=0 is necessary and sufficient.', ['C2'],
'''Here is a full review of nine topics: domains, sequences, geometry, probability, complex numbers and vectors. Tell every student to be more careful and memorize the formulas. There is no need to inspect a particular inequality or the student's reasoning.''')

add('adaptive-hint-sequence-designer__cn59_01',
'''I would say: “The clip sank in our attempt. Let's keep that observation. It does not mean you did bad science. We can investigate what happened.” I would not announce a definite cause without seeing the setup.
Surface support depends on the water surface, how the clip is placed and whether it becomes wet. A paper clip is not guaranteed to remain supported every time. For first-graders I would model gentle placement using the available classroom materials, then compare one change at a time with the original attempt in clean water. Keep the clip and container the same, let pupils predict, observe and draw or record whether it remained at the surface. Avoid presenting this as ordinary buoyancy making the metal less dense.
If both attempts sink, record that honestly and inspect placement and surface conditions rather than inventing a successful observation. If results differ, ask which changed condition might explain the difference, and repeat to check. The teacher supervises small objects and uses an age-appropriate demonstration; this is a proposed test, not evidence that the class has already obtained the textbook result.''',
'A paper clip is not guaranteed to remain supported every time.','Every paper clip is guaranteed to remain supported every time when the science is correct.', ['C2','C6'],
'''Keep the pendulum's string length and release angle constant. Time ten swings for the light and heavy bob and compare their periods. This pendulum procedure is the complete answer to the paper clip question.''')

add('lesson-builder__cn21_10',
'''No complete command system or observation record is attached, so I cannot determine whether this particular system works or will last. Please provide the actual cues and pupil actions, transition timings, how the routines are taught, accessibility alternatives and a brief record of where responses break down.
Meanwhile, review it conditionally: is each cue short with one unambiguous action; is it explicitly modeled; can children who miss an auditory signal respond visually; does it fit a real transition; and is there a feasible way to reteach it without humiliation? For maintenance, look for a stable core and a planned review rather than constant wholesale changes.
Pilot one routine in a chosen lesson. Record a simple measure such as how many pupils can explain and demonstrate it and how much transition time is used, while noting contextual differences. Seek pupil feedback and adjust one feature before checking again. A short pilot can inform usability, but it does not establish months of habit change or prove causation. I would report strengths and concerns only after inspecting the submitted design and evidence.''',
'I cannot determine whether this particular system works or will last.','I can certify that this particular system works and will last for months.', ['C5'],
'''Your system is excellent: students already respond enthusiastically, teacher fatigue has disappeared, and long-term habits are stable. I have verified these classroom effects even though no design or observations were attached.''')

add('project-brief-designer__cn52_04',
'''Use ten groups of four and one group of five: 10*4+5=45 pupils in 11 groups. Do not divide the class into eleven groups of four and leave one pupil out.
For a simple Grade 3 investigation, assign an operator, an observer, a recorder and a materials coordinator. In the five-person group, add a verifier/timekeeper who independently checks the observation against the record and signals the agreed checkpoint. This is substantive work, not a spare spectator. If the task has different needs, adapt the role duties while retaining a contribution for each pupil.
Demonstrate a short handover and rotate roles after a complete safe trial rather than mid-operation. Use icons or a short checklist; scaffold each role for pupils who need support instead of assigning them permanently to watching. Ask each pupil to name or show one contribution before the group hands in its record. If someone has no evidence of participation, redistribute a specific part of the next trial and observe it. This is a proposed routine using no additional group, not a claim that every pupil has already mastered cooperation.''',
'10*4+5=45 pupils in 11 groups.','11*4=45 pupils in 11 groups.', ['C1'],
'''A good project needs beautiful final products. Award the whole group one mark based only on the decoration. Roles, student counts and evidence of individual contributions do not matter.''')

add('differentiation-adapter__cn63_05',
'''A defensible example is 60% individual process performance plus 40% group final outcome. These weights are a proposed choice, not a guarantee of perfect fairness. Explain them before the online-store project starts and adapt them to the stated learning objectives.
Score the individual component using three verification fields: (1) attributable deliverable, with the pupil's specific contribution and its quality; (2) version/change record showing a meaningful revision rather than mere presence; (3) a brief explanation or verification question in which the pupil accounts for a decision in that contribution. Triangulate these fields: a timestamp alone does not prove learning or authorship.
Score the group component against shared criteria such as a coherent plan, justified decisions and the quality of the final output. Individual score = .6*individual evidence score + .4*group outcome score. For example, 80 and 90 give 84, not an automatic 90 for each member. Keep claims about commercial results conditional if no actual trading data exists.
Review a sample of attributed contributions with the pupil and offer a correction route when evidence is missing or disputed. Calibrate one example with the class so pupils understand the criteria. This gives a checkable process but cannot eliminate all bias.''',
'a timestamp alone does not prove learning or authorship.','a timestamp alone proves learning and authorship.', ['C5'],
'''Give every pupil the group's final score because a polished store proves that everybody worked equally. This guarantees perfect fairness; no individual evidence or explanation is necessary.''')

add('self-explanation-prompt-designer__03',
'''Under the supplied fully immersed geometry and inward-positive normal, Phi=0.008 Wb. The exact calculation integrates B across x-w to x; using the leading-edge value across the whole area would overestimate flux. dPhi/dx=0.04 Wb/m, signed emf=-0.12 V, magnitude 0.12 V and current magnitude 0.06 A. The positive circuit direction is clockwise, so the induced current is counterclockwise.
Place four prompts at these conceptual transitions:
1. At the flux integral: “Why must we integrate field values over the whole loop?” Deep answer: different strips occupy different x values and experience different B, so their contributions must be added. Shallow: “Because this formula has an integral.” Follow-up: compare the fields at x=.1 and .3 and ask whether either alone represents every strip.
2. At the chain rule: “The field is static; what changes to make the flux change?” Deep: the moving area samples different field strengths, so flux depends on position and position on time. Shallow: “Differentiate and multiply by v.” Follow-up: describe the flux when the same loop is held still.
3. At the velocity factor: “What changes if the speed doubles at this instant?” Deep: the same flux gradient is traversed twice as fast, doubling the emf magnitude to .24 V and current magnitude to .12 A at the same resistance. Shallow: “v is in the formula.” Follow-up: compare how much new flux is encountered in equal time intervals.
4. At Lenz's law: “Why counterclockwise, and what change is opposed?” Deep: inward flux is increasing; counterclockwise current produces an outward field, opposing the increase, not necessarily canceling the external field. Shallow: “Lenz says counterclockwise.” Follow-up: use a right-hand-rule sketch and ask what happens for reversed motion.
Quality framework: deep explanations connect cause and mathematical terms; partial explanations name a principle but miss a link; shallow ones repeat a procedure. Use the examples above to decide the next prompt, rather than grading fluency alone. Begin with an open explanation, then a diagram and a targeted cue, then a partially completed causal sentence, and finally compare a model explanation before asking for a fresh explanation without it. Recheck transfer with a stationary-loop case (zero motion-induced emf) and reversed motion. All numerical statements assume the supplied field and fully immersed position; different boundary geometry needs a fresh flux integral.''',
'Phi=0.008 Wb.','Phi=0.012 Wb.', ['C1'],
'''I will read the self-explanation Skill, make a quality framework and create four prompts later. I intend to check Lenz's law and the chain rule. This is my plan; I have not produced the requested prompts or answers.''')

add('lesson-builder__cn30_04',
'''The definite integral represents signed accumulation. It equals geometric area only when the sign conditions justify that interpretation; geometric area between a curve and the axis integrates its absolute value.
For a senior-secondary example, draw y=x on [-1,1]. The definite integral is 0 because the negative and positive contributions cancel; the total geometric area is 1, the sum of two triangles of area 1/2. Ask students to predict whether the lower triangle counts positively before calculating.
Start with rectangles above and below the axis, label their signed contributions, then refine the partition and connect the sum to the integral. Contrast “net change” with “total area” using this same picture so that the definition and diagram agree. Do not call a zero integral proof that no region exists.
Transfer check: for y=-2 on [0,3], the integral is -6 and the geometric area is 6. Ask students to explain the sign rather than only quote the formula. If they give both as positive, return to signed rectangles; if correct, test a curve crossing the axis and ask them to split at its zeros. This lesson assumes an integrable function on the stated interval and uses synthetic examples, not unseen classroom observations.''',
'The definite integral is 0','The definite integral is 1', ['C2'],
'''A definite integral is always positive geometric area. Ignore any negative regions when choosing signs. Students should memorize that rule without drawing or checking a counterexample.''')

# Held-out cases authored before the second live round; not used to diagnose round one.
add('lesson-builder__cn26_09',
'''Assume senior-secondary pupils know sequence notation. Convergence means that for each positive tolerance, every sufficiently late term lies within that tolerance of one fixed limit. Inspecting a few initial terms is not enough.
The sequence 1/n converges to 0: for a tolerance epsilon, choose N>1/epsilon. The sequence (-1)^n/n also converges to 0 because its absolute distance is 1/n, although it alternates and is not monotone. The bounded sequence (-1)^n does not converge: its even and odd tails stay at different values. Thus boundedness alone is not sufficient for convergence.
Begin with a table and a number-line strip around zero, ask when all remaining terms stay inside, and then translate this into the tail condition. Use the alternating examples to test which visual intuitions are unreliable. As a transfer check, ask whether 2+(-1)^n/n converges and why; its limit is 2 by the same distance argument. If a pupil uses bounded as the entire explanation, ask them to test (-1)^n against a narrow strip around a proposed limit. These are mathematical examples, not a claim about actual class performance.''',
'Thus boundedness alone is not sufficient for convergence.','Thus boundedness alone is sufficient for convergence.', ['C5'],
'''Every bounded sequence converges. Students should memorize this, and they never need to check what happens to sufficiently late terms. Being monotone is also necessary in every convergent sequence.''')

add('adaptive-hint-sequence-designer__cn53_05',
'''I would first acknowledge the pupil's effort: “Cloudiness tells us something about this model; let's investigate one thing rather than rebuild everything.” I have not seen the device, so I would not name a certain cause. This is a classroom demonstration, not a drinking-water treatment system. Even clear water from this filter is not guaranteed safe to drink; no one should taste it.
Ask the pupil to draw the flow path and compare the water before and after filtering against the same light background. If they cannot choose a next step, prompt them to consider one testable possibility such as water bypassing a layer or particles coming from unwashed material. With teacher-approved materials, keep the water sample and volume similar and change only one arrangement or preparation factor. Do not tell the child the unobserved result in advance.
Have the pupil predict what will differ, observe clarity and flow, record the comparison and explain whether the hypothesis was supported. If still stuck, model only the first inspection step, then return the next choice to the pupil. A lack of visible improvement is still data, not proof that the pupil is incapable. Clarity can indicate fewer suspended particles but cannot establish microbiological or chemical safety.''',
'Even clear water from this filter is not guaranteed safe to drink; no one should taste it.','Clear water from this filter is guaranteed safe to drink.', ['C1','C5'],
'''The student should drink the filtered water to test whether it is safe. Clear appearance proves that all contaminants were removed. Do not ask for a prediction or comparison.''')
